### Numpy

In [38]:
#To install numpy

In [39]:
!pip install numpy                                   

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [41]:
arr = np.array([1 ,2 , 3])
print(arr)
print(type(arr))
print(len(arr))

[1 2 3]
<class 'numpy.ndarray'>
3


In [42]:
arr1 = np.array(['Pratik' , 'Bhoot' , 'Redemption' , 1 ])
print(arr1)
print(type(arr1))

['Pratik' 'Bhoot' 'Redemption' '1']
<class 'numpy.ndarray'>


In [43]:
#TO force datatype

In [44]:
arr1 = np.array([ 7.2 ,1 ,2 ,3 ], dtype = int)
print(arr1)
print(type(arr1))

[7 1 2 3]
<class 'numpy.ndarray'>


In [68]:
l = []
for i in range(0,21,2):
    l.append(i)
arr = np.array(l)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [83]:
np.zeros(10 , dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
arr = []
for i in range(11):
    arr.append(0)
nump = np.array(arr)
print(nump)

[0 0 0 0 0 0 0 0 0 0 0]


In [88]:
a = np.ones(10 , dtype = int)
print(a)
print(type(a))

[1 1 1 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>


In [101]:
np.eye((8) , dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [111]:
arr6 = np.full((3,3) , '*')
print(arr6)

[['*' '*' '*']
 ['*' '*' '*']
 ['*' '*' '*']]


In [115]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [117]:
np.random.seed(1000)

np.random.randint(0,20, (3,5))

array([[19,  7,  0,  1,  0],
       [13,  8,  9,  4, 13],
       [15, 10,  9,  4, 18]])

In [124]:
x = np.random.randint(0,20, (3,5))
print(x.ndim)
print(x.shape)
print(x.size)
print(x)

2
(3, 5)
15
[[ 0  3  3 11  3]
 [ 6  4  2  4  4]
 [18 17 12 15 18]]


In [148]:
np.random.seed(45)
x = np.random.randint(0,10, (3,3))
print(x)
x[1:4 , 1:10]

[[3 0 5]
 [3 4 9]
 [8 1 5]]


array([[4, 9],
       [1, 5]])

In [162]:
arr = np.random.randint(5,20 , (4,4))
arr.reshape(8,2)

array([[12, 12],
       [ 9, 14],
       [14, 14],
       [16, 14],
       [17, 12],
       [15,  7],
       [12, 14],
       [19, 19]])

In [ ]:
#axis = o for rows and axis = 1 is for coulumn

In [167]:
# x= np.eye(4)
# y = np.zeros(9 , dtype = int).reshape(3,3)

# print(np.concatenate([x,y]))

In [169]:
x = [1,2,3]
y = [ 
[5,6,7],
[8,15,8]
]

# vstack - axis
# hstack - axis

In [171]:
np.vstack([y,x])

array([[ 5,  6,  7],
       [ 8, 15,  8],
       [ 1,  2,  3]])

In [177]:
x = np.array([0,1,2,3,4,5,6])

print(x[2*x == x**2])

[0 2]


In [189]:
x = np.array([0,1,2,3,4,5,6])

print(np.any(x>2))
(np.all(x<6))

True


False

In [201]:
arr = np.random.randint(5,20 , (4,4))

print(np.all(x>-2))
print()
print(np.any(x**2 == x*2))
print()
print(arr)

True

True

[[ 9 17 18  8]
 [15  7 16 10]
 [12 18 16 14]
 [ 7 10 13  5]]


#### Splitting

In [4]:
x = [1,2,3,99,99,3,2,1]
x1 ,x2,x3, x4 = np.split(x, [2,4,6])
print(x1,x2,x3)

[1 2] [ 3 99] [99  3]


In [6]:
np.ones(20 ,dtype = int)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [9]:
print(np.absolute(x))
print()

print(np.abs(x))


[ 1  2  3 99 99  3  2  1]

[ 1  2  3 99 99  3  2  1]


#### Absolute function

In [15]:
arr = np.array([])
l= []
for i in range(-100,101):
    l.append(i)
print(np.absolute(l))

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1   0   1   2   3   4   5   6   7
   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25
  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61
  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100]


In [16]:
arr = np.array([])
l= []
for i in range(-100,101):
    l.append(i)
print(np.abs(l))

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1   0   1   2   3   4   5   6   7
   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25
  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61
  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100]


In [43]:
big_array = np.random.rand(1000)

%timeit sum(big_array)
%timeit np.sum(big_array)
%timeit big_array.sum()

146 µs ± 3.64 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
7.84 µs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
3.81 µs ± 43.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
arr = np.array([])
l= []
for i in range(0,101):
    l.append(i)
    
arr = np.array(l) 
arrsum = arr.sum()
print(arrsum/len(range(0,101)))


50.0


In [51]:
print(np.min(l))
print(np.max(l))

0
100


In [55]:
M = np.ones((2,3))
A = np.arange(3)

print(M, end ='\n\n')
print(A, end = '\n\n')
print(M+A, end = '\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[0 1 2]

[[1. 2. 3.]
 [1. 2. 3.]]



In [60]:
# M = np.ones((2,3))
# A = np.arange(2)

# print(M, end ='\n\n')
# print(A, end = '\n\n')
# print(M+A, end = '\n\n')

#NOT POSSIBLE

In [61]:
M = np.arange(3)
A = np.arange(3).reshape(3,1)
print(M+A, end = '\n\n')

[[0 1 2]
 [1 2 3]
 [2 3 4]]

